### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by nikolockenvitz** [rcjberlin/rcj-server#1]
The CORS header was not updated everywhere. I would suggest to create a function `getCORSResponse()` so that this can be used everywhere.
https://github.com/rcjberlin/rcj-server/blob/f67d76b0053b8ac09df6cb939b970633fbec5b9a/src/rcj_flask.py#L58-L61
https://github.com/rcjberlin/rcj-server/blob/f67d76b0053b8ac09df6cb939b970633fbec5b9a/src/rcj_flask.py#L69-L72
I think it would be ok (at least for testing) to have both URLs in CORS header.

**Comment by mb** [comment]
Using [flask-cors](https://flask-cors.readthedocs.io/en/latest/) now.
